services:
  maps:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
      - ../data:/app/data
      - ../output:/app/output
    environment:
      - PYTHONPATH=/app/scripts
      - PGUSER=docker
      - PGDATABASE=gis
      - STADIA_API_KEY=${STADIA_API_KEY}
      - THUNDERFOREST_API_KEY=${THUNDERFOREST_API_KEY}
    network_mode: host
    stdin_open: true
    tty: true
    working_dir: /app

  postgres:
    image: postgis/postgis:14-3.2
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
