name: "spain_provinces"
title: "Provincias de España"
description: "Map of Spain's 50 provinces with clear boundaries and labels"

# Output settings
output_width: 4000
output_height: 2250
background_color: "#f0f8ff"

# Map bounds (Mainland Spain - excludes Canary Islands)
# Adjusted to match 16:9 aspect ratio for proper basemap alignment
bounds:
  south: 4163348   # Southern Spain (Andalusia)
  north: 5470528   # Northern Spain (Asturias/Basque Country)
  west: -1433815   # Expanded west to match 16:9 ratio
  east: 882238     # Expanded east to match 16:9 ratio

# Terrain basemap
basemap:
  source: "OpenTopoMap"  # Topographical terrain with elevation shading
  alpha: 0.8              # Allow terrain to show through
  zoom: 8                 # Good balance of detail and readability

# Data layers
layers:
  countries:
    file: "raw/ne_10m_admin_0_countries.shp"
    filter: "NAME == 'Spain'"
    style:
      fill_color: "none"     # Let terrain show through
      stroke_color: "#2c2c2c"
      stroke_width: 3
      opacity: 1.0
      zorder: 1

  provinces:
    file: "processed/mainland_spain_provinces.geojson"
    style:
      fill_color: "none"     # Let terrain show through
      stroke_color: "#8b0000" # Dark red for strong contrast
      stroke_width: 2
      opacity: 0.9
      zorder: 2
    labels:
      field: "name"
      font_size: 10
      font_color: "white"
      font_weight: "bold"
      outline_width: 1
      outline_color: "auto"

  coastline:
    file: "raw/ne_10m_coastline.shp"
    style:
      fill_color: "none"
      stroke_color: "#1f77b4"
      stroke_width: 2
      opacity: 1.0
      zorder: 3

# Key provinces to highlight (you can customize this list)
highlight_provinces:
  - "Asturias"
  - "Madrid"
  - "Barcelona"
  - "Valencia"
  - "Sevilla"
  - "Bilbao"
  - "A Coruña"
  - "Alicante"
  - "Málaga"
  - "Las Palmas"
