name: "spain_provinces"
title: "Provincias de España"
description: "Map of Spain's 50 provinces with clear boundaries and labels"

# Output settings
output_width: 4000
output_height: 2250
background_color: "#f0f8ff"

# Map bounds (Spain)
bounds:
  west: -1100000
  east: 500000
  south: 4200000
  north: 5500000

# Data layers
layers:
  countries:
    file: "raw/ne_10m_admin_0_countries.shp"
    filter: "NAME == 'Spain'"
    style:
      fill_color: "#f0f8f0"
      stroke_color: "#333333"
      stroke_width: 2
      opacity: 1.0
      zorder: 1

  provinces:
    file: "raw/ne_10m_admin_1_states_provinces.shp"
    filter: "admin == 'Spain'"
    style:
      fill_color: "#e8f4e8"
      stroke_color: "#555555"
      stroke_width: 1.5
      opacity: 0.9
      zorder: 2
    labels:
      field: "name"
      font_size: 24
      font_color: "white"
      font_weight: "bold"

  coastline:
    file: "raw/ne_10m_coastline.shp"
    style:
      fill_color: "none"
      stroke_color: "#1f77b4"
      stroke_width: 2
      opacity: 1.0
      zorder: 3

# Key provinces to highlight (you can customize this list)
highlight_provinces:
  - "Asturias"
  - "Madrid"
  - "Barcelona"
  - "Valencia"
  - "Sevilla"
  - "Bilbao"
  - "A Coruña"
  - "Alicante"
  - "Málaga"
  - "Las Palmas"
